format_version: 3
pipelines:
  spring-web-boot-support:
    lock_behavior: lockOnFailure
    group: Spring Support
    materials:
      repo:
        git: https://github.com/pipo411/AG_SpringWebBootSupport.git
        branch: gocd
    stages:
      - Build:
          jobs:
            Building:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - "clean"
                      - "assemble"  
              artifacts:
                - build:
                    source: build/libs/*.jar
                    destination: buildJar   
      - Test:
          jobs:
            Unit_Test:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - clean
                      - test
              artifacts:
                - build:
                    source: build/reports/tests/test/index.html
                    destination: html
                - test:
                    source: build/test-results/test/*.xml
                    destination: xml
              tabs:
                unit_test: xml/index.html
                htmlReports: html/index.html
                
      